#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  Regenerate the two publishing branches from `dev`.
#
#  THE REPOSITORY HAS THREE BRANCHES AND ONLY ONE OF THEM IS EDITED
#
#    dev       everything — curriculum/, site/, process/, examples/, tools/.
#              This is the source of truth. All work happens here.
#
#    main      the student-facing robot project, with the Gradle build at the
#              REPO ROOT. Clone it, open it in WPILib VS Code, and the Build and
#              Simulate buttons work — they require the Gradle project to be the
#              workspace root (wpilibsuite/vscode-wpilib#847), which is why the
#              contents are promoted out of curriculum/ rather than left nested.
#
#    website   the MkDocs site laid out for a static host (Vercel, Netlify,
#              Cloudflare Pages, GitHub Pages). mkdocs.yml at the root, docs/
#              beside it, and the parts of curriculum/ the pages include.
#
#  WHY GENERATE THEM
#
#  The obvious alternative is to maintain all three by hand. That works for
#  about a week. The moment somebody edits a lesson on dev, main and website are
#  stale, and nothing tells you — the branches just quietly drift until a student
#  clones a curriculum that does not match the site.
#
#  So main and website are OUTPUT. Editing them directly is a mistake, and this
#  script overwrites whatever is there.
#
#  USAGE
#      tools/publish-branches.sh            # regenerate both
#      tools/publish-branches.sh main       # just one
#      tools/publish-branches.sh website
#
#  Afterwards:  git push origin dev main website
#
#  History is preserved — each run adds a normal commit to each branch, so no
#  force-push is ever needed.
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"
cd "$REPO"

SOURCE_BRANCH="dev"
targets=("${@:-}")
if [[ -z "${targets[0]:-}" ]]; then
  targets=(main website)
fi

# ─── Safety ─────────────────────────────────────────────────────────────────
if [[ -n "$(git status --porcelain)" ]]; then
  echo "✗ Working tree is dirty. Commit or stash first — this script switches" >&2
  echo "  branches and would carry your changes across." >&2
  exit 1
fi

if ! git rev-parse --verify --quiet "$SOURCE_BRANCH" >/dev/null; then
  echo "✗ No '$SOURCE_BRANCH' branch. That is the source of truth; create it first." >&2
  exit 1
fi

START_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
SOURCE_SHA="$(git rev-parse --short "$SOURCE_BRANCH")"
STAGE="$(mktemp -d)"
trap 'rm -rf "$STAGE"; git switch --quiet "$START_BRANCH" 2>/dev/null || true' EXIT

# Export dev's tree once, so every target is built from the same snapshot and
# from committed content rather than from whatever is lying around on disk.
git archive "$SOURCE_BRANCH" | tar -x -C "$STAGE"
echo "Building from $SOURCE_BRANCH @ $SOURCE_SHA"

# ─── Helpers ────────────────────────────────────────────────────────────────

# Switch to a branch, creating it from dev if it does not exist yet.
prepare_branch() {
  local branch="$1"
  if git rev-parse --verify --quiet "$branch" >/dev/null; then
    git switch --quiet "$branch"
  else
    git switch --quiet --create "$branch" "$SOURCE_BRANCH"
  fi
  # Remove every tracked file. The branch's contents are entirely replaced on
  # each run; anything not re-added below is meant to be gone.
  git rm -r --quiet --cached . >/dev/null 2>&1 || true
  find . -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
}

commit_branch() {
  local branch="$1" what="$2"
  git add -A
  if git diff --cached --quiet; then
    echo "  = $branch already matches $SOURCE_BRANCH @ $SOURCE_SHA"
    return
  fi
  git commit --quiet -m "Publish $what from $SOURCE_BRANCH @ $SOURCE_SHA

Generated by tools/publish-branches.sh. Do not edit this branch directly —
the next run overwrites it. All work happens on $SOURCE_BRANCH."
  echo "  ✓ $branch updated"
}

# ─── main: the robot project, Gradle build at the root ──────────────────────
build_main() {
  echo "→ main"
  prepare_branch main

  # curriculum/* promoted to the root, including dotfiles.
  ( shopt -s dotglob; cp -R "$STAGE"/curriculum/* . )

  # A short pointer so somebody landing here knows where the rest lives.
  cat >> README.md <<'EOF'

---

## Where this branch comes from

This branch is **generated**. It is the student-facing robot project, with the
Gradle build at the repository root so that WPILib's VS Code commands work when
you open the folder directly.

- Everything — this project plus the website, the design documents and the
  browser playgrounds — lives on the **`dev`** branch.
- The website, laid out for a static host, is on the **`website`** branch.

Do not send pull requests against this branch; it is overwritten by
`tools/publish-branches.sh` on every publish. Work on `dev`.
EOF

  commit_branch main "the robot project"
}

# ─── website: MkDocs laid out for a static host ─────────────────────────────
build_website() {
  echo "→ website"
  prepare_branch website

  # mkdocs.yml, docs/, requirements.txt and the build tooling move to the root.
  ( shopt -s dotglob; cp -R "$STAGE"/site/* . )
  rm -rf _site .venv

  # The lesson pages include lesson text and real source files out of
  # curriculum/ via pymdownx.snippets, so that tree has to travel with them.
  # Only the parts the site actually reads.
  mkdir -p curriculum/lessons curriculum/src
  cp -R "$STAGE"/curriculum/lessons/. curriculum/lessons/
  cp -R "$STAGE"/curriculum/src/. curriculum/src/
  cp "$STAGE"/curriculum/OFFLINE.md curriculum/

  # The browser playgrounds are served at /examples/. On dev that is a symlink
  # created by serve.sh; a host needs real files.
  mkdir -p docs/examples
  cp -R "$STAGE"/examples/. docs/examples/

  # snippets base_path pointed at the parent directory when mkdocs.yml lived in
  # site/. At the root, curriculum/ is a sibling.
  python3 - <<'PY'
import pathlib
p = pathlib.Path("mkdocs.yml")
s = p.read_text()
s = s.replace("""      base_path:
        - ..
        - docs""", """      base_path:
        - .
        - docs""")
p.write_text(s)
PY

  cat > vercel.json <<'EOF'
{
  "$schema": "https://openapi.vercel.sh/vercel.json",
  "buildCommand": "pip install -r requirements.txt && mkdocs build",
  "outputDirectory": "_site",
  "framework": null,
  "cleanUrls": true,
  "trailingSlash": true
}
EOF

  cat > .gitignore <<'EOF'
_site/
.venv/
__pycache__/
.DS_Store
EOF

  cat > README.md <<'EOF'
# FRCProgramming — website

The MkDocs site, laid out for a static host. **This branch is generated** by
`tools/publish-branches.sh` on the `dev` branch; edits made here are overwritten
on the next publish.

## Layout

```
mkdocs.yml          site config (snippets resolve against this directory)
docs/               the pages
docs/examples/      the browser playgrounds, served at /examples/
curriculum/         lesson text and robot source, included by the lesson pages
requirements.txt    mkdocs + material + pymdown-extensions
vercel.json         build command and output directory
```

`curriculum/` is here because every lesson page **includes** the canonical lesson
text and the real Java source rather than copying it. That is what stops the site
and the project a student edits from drifting apart, and it means the site cannot
build without those files.

## Build it locally

```bash
python3 -m venv .venv && source .venv/bin/activate
pip install -r requirements.txt
mkdocs serve          # http://localhost:8000
mkdocs build --strict # -> _site/
```

`--strict` turns a missing include into a build failure, which is what you want:
a moved source file should break the build rather than silently produce an empty
code block.

## Deploy

Any static host works. `vercel.json` is pre-configured:

| Setting | Value |
|---|---|
| Build command | `pip install -r requirements.txt && mkdocs build` |
| Output directory | `_site` |
| Install command | *(leave empty — the build command installs)* |

Set `site_url` in `mkdocs.yml` to the deployed URL once you have it, so search
and canonical links point at the right place.
EOF

  commit_branch website "the website"
}

# ─── Run ────────────────────────────────────────────────────────────────────
for t in "${targets[@]}"; do
  case "$t" in
    main) build_main ;;
    website) build_website ;;
    *) echo "✗ Unknown target '$t'. Use: main, website" >&2; exit 2 ;;
  esac
done

git switch --quiet "$START_BRANCH"
echo
echo "Done. Publish with:"
echo "    git push origin $SOURCE_BRANCH ${targets[*]}"
